name: debugger-action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}. ${{ secrets.GITHUB_TOKEN }}"
     - name: Setup Debug Session
       uses: csexton/debugger-action@master
